# This is a basic workflow to help you get started with Actions

name: CICICICI
env:
  APPLICATION_NAME   : "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-version-${{github.sha}}"

on:
  push:
    branches:
      - master
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Message
        run: echo "Hello World from Testing job"
      - name: List current folder
        run: ls -la
        run: pwd
        
      - name: Execure few comands
        run : 
          echo "Hello message1"
          echo "Hello message2" 
          echo "Application name ${{ env.APPLICATION_NAME }}"
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    steps:
      - name: Print Hello Message
        run: echo "Hello World from Deploy job"
      
      - name: Printing Deployment packege
        run : echo "Deploy packege name is ${{ env.DEPLOY_PACKAGE_NAME }}"
     
